name: classification
num_tokens: 512
tokenizer_cls: cl-tohoku/bert-base-japanese-whole-word-masking

data:
  ene_name: shinra2022_Categorization_train_20220511.jsonl
  cirrus_name: jawiki-20190121-cirrussearch-content.json.gz