defaults:
  - optim: adamw
  - scheduler: linear_with_warmup

name: classification

dataloader:
  num_workers: 16
  train:
    batch_size: 64
    shuffle: true
  eval:
    batch_size: 256
  

model:
  num_tokens: 512

data:
  dataset_dir: jawiki-20190121-cirrussearch-content.json.gz_prep
  dev_size: 1000