FROM nvcr.io/nvidia/pytorch:20.11-py3
LABEL maintainer=k141303

RUN pip3 install --upgrade pip
RUN pip3 install \
    hydra-core==1.1.1 \
    tensorboardx==2.1 \
    transformers==4.13.0 \
    mlflow==1.22.0 \
    Janome==0.4.1 \
    subword-nmt==0.3.7