hydra:
  run:
    dir: outputs 

defaults:
  - train: classification

train:
  seed: 1234
  debug_mode: false

  total_updates: 30000
  eval_updates: 1000
  use_checkpoint: true
  checkpoint_updates: 1000
  log_updates: 10

  gradient_accumulation_steps: 1

  data:
    dir: data

  model:
    dir: model/roberta_base_wiki201221_janome_vocab_32000

  device:
    fp16: true
    fp16_opt_level: O1
    no_cuda: false
    device: null # Store during execution
    n_gpu: null # Store during execution